---
- name: Copy configuration files
  template:
    src: "Corefile-{{ item }}"
    dest: /etc/coredns
    owner: root
    group: root
    mode: 0644
  loop: "{{ coredns_config_names }}"
  notify: restart coredns

- name: Copy zone files
  template:
    src: "{{ item }}"
    dest: /etc/coredns/zones
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ coredns_zone_files_paths }}"
